trigger: none
pool:
  name: agent-ka-jhoond
jobs:
  - job: job1
    displayName: BuildJob
    workspace:
      clean: outputs
    steps: 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "This is my first job"

  - job: job2
    displayName: terraform init
    workspace:
      clean: outputs
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment'
        backendServiceArm: 'kk-service-connection'
        backendAzureRmResourceGroupName: 'kk-rg'
        backendAzureRmStorageAccountName: 'storageacc1234'
        backendAzureRmContainerName: 'kkcontainer'
        backendAzureRmKey: 'st.tfstate'