trigger: none
pool:
  name: agent-ka-jhoond
jobs:
  - job: job1
    displayName: BuildJob
    workspace:
      clean: outputs
    steps: 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "This is my first job"