trigger: none
pool:
  -name: agent-ka-jhoond
jobs:
  - job: job1
    displayName: BuildJob
    workspace:
      clean: output
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo My first job